/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/_page-hub/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getManagerStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_page-hub/api/v1/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_page-hub/api/v1/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Requests a storage observation. Joins an already running scan instead of queueing another one; answers when the joined scan completes. */
        post: operations["requestRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_page-hub/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/_page-hub/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Inventory: {
            projects: components["schemas"]["InventoryProject"][];
            /** @description Latest complete bucket observation, or null before the first successful scan. */
            observation: components["schemas"]["BucketObservation"] | null;
            refresh: components["schemas"]["RefreshState"];
        };
        RefreshState: {
            /** @description Whether a full storage scan is currently running. */
            running: boolean;
            /**
             * @description Outcome of the most recent scan attempt; provider details are never included.
             * @enum {string}
             */
            lastOutcome: "never" | "succeeded" | "unavailable" | "misconfigured" | "failed";
        };
        InventoryProject: {
            id: string;
            prefix: string;
            displayName: string;
            description: string;
            publications: components["schemas"]["InventoryPublication"][];
        };
        InventoryPublication: {
            id: string;
            path: string;
            displayName: string;
            description: string;
            entryPoint: string;
            /** @enum {string} */
            routingMode: "exact_file" | "directory_index" | "fallback";
            /** @description Accepted size in bytes from the current manifest. */
            size: number;
            /** Format: date-time */
            contentChangedAt: string;
            /** @description Observed storage state from the latest complete bucket observation. */
            observation: components["schemas"]["PublicationObservation"] | null;
        };
        PublicationObservation: {
            /** @enum {string} */
            state: "in_sync" | "drifted" | "missing";
            /** @description Sum of observed sizes of the Publication's objects found in storage; null when none were found. */
            observedSize: number | null;
            /** @description Bounded, deterministic summary of the differences from the accepted manifest. */
            statusDetail: string;
        };
        BucketObservation: {
            /** Format: date-time */
            observedAt: string;
            /**
             * @description Storage-mutation lock this observation implies for later storage mutations.
             * @enum {string}
             */
            mutationLock: "none" | "global" | "publication";
            usage: components["schemas"]["BucketUsage"];
            /** @description True when the observation is older than five minutes. */
            stale: boolean;
        };
        BucketUsage: {
            /**
             * Format: int64
             * @description Configured bucket quota in bytes.
             */
            quotaBytes: number;
            /**
             * Format: int64
             * @description Exact usage of the complete bucket observation.
             */
            totalBytes: number;
            /**
             * Format: int64
             * @description Usage of the accepted Publication manifests.
             */
            acceptedBytes: number;
            /**
             * Format: int64
             * @description Usage of unexpected objects outside every accepted manifest.
             */
            unclaimedBytes: number;
        };
        StorageStatus: {
            /** @enum {string} */
            status: "reachable" | "unavailable" | "misconfigured";
        };
        ManagerStatus: {
            version: string;
            storage: components["schemas"]["StorageStatus"];
        };
        HealthStatus: {
            /** @constant */
            status: "ok";
            version: string;
        };
        ReadinessStatus: {
            /** @enum {string} */
            status: "ready" | "degraded";
            /** @enum {string} */
            storage: "reachable" | "unavailable" | "misconfigured";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getManagerStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current manager and storage status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagerStatus"];
                };
            };
            /** @description Trusted gateway assertion missing or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog-backed inventory of Projects and Publications with the latest bucket observation and refresh progress. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inventory"];
                };
            };
            /** @description Trusted gateway assertion missing or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The catalog inventory is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    requestRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current refresh state after the requested (or joined) scan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshState"];
                };
            };
            /** @description Trusted gateway assertion missing or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The observation service is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is serving requests. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
            /** @description Trusted gateway assertion missing or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manager and bucket are reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description Trusted gateway assertion missing or invalid. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Manager is serving but storage is unavailable or misconfigured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
}
